### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by prosaic-toast** [standardebooks/h-rider-haggard_she#1]
- chapter 9: "been *worthy* a hundred" → worth
- chapter 16: "after *you* hast gone" → thou
- chapter 18: "to *whom* who" → him
- chapter 18: "himself *from* therefrom" → delete from
- chapter 27: "fellow at *collage*" → college
- chapter 27: "stared *as* in the face" → us

**Comment by acabal** [comment]
Thanks, these should be fixed now!
